/**
 * Regenerate `src/client/logo.ts` from `assets/logo-128.png`.
 *
 * The web shell serves a plugin exactly one file (`/plugins/<id>/client.js`)
 * with no static-asset route, so the logo ships inside the bundle as a data
 * URL — the same "anything outside the module table is inlined" rule the
 * client build already follows.
 *
 * Usage: node scripts/embed-logo.mjs
 * (Resize first when the source image changes:
 *   sips -z 128 128 logo.png --out assets/logo-128.png)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const png = readFileSync(join(here, '..', 'assets', 'logo-128.png'))
const url = `data:image/png;base64,${png.toString('base64')}`

const out = `/**
 * The plugin logo as a data URL, generated by \`scripts/embed-logo.mjs\` from
 * \`assets/logo-128.png\` (the root \`logo.png\` resized to 128x128). Do not edit
 * by hand — regenerate instead. See that script for why the image is embedded
 * rather than served.
 */
export const LOGO_URL =
  '${url}'
`

writeFileSync(join(here, '..', 'src', 'client', 'logo.ts'), out)
console.log(`src/client/logo.ts written (${url.length} chars)`)
